# Python

![title](python.png)

## Création de variables

In [1]:
a = 3
b = 2
c = a + b
c

5

In [2]:
a += 2
a

5

## Collections

## Listes

### Création

In [3]:
l = [1, 2, 3]
l

[1, 2, 3]

In [4]:
len(l)

3

### Sélection

In [5]:
l[0]

1

In [6]:
l[1]

2

In [7]:
l[-1]

3

In [8]:
l[1:]

[2, 3]

In [9]:
l[:2]

[1, 2]

### Application d'une fonction

In [10]:
def increment(x):
    return x + 1

list(map(increment, l))

[2, 3, 4]

In [11]:
map(increment, l)

In [12]:
list(map(lambda x: x + 1, l))

[2, 3, 4]

In [13]:
[x + 1 for x in l]

[2, 3, 4]

### Range

In [14]:
range(10)

range(0, 10)

In [15]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
list(range(2, 20, 2))

[2, 4, 6, 8, 10, 12, 14, 16, 18]

## Dictionnaires

In [17]:
eleve = {"Prénom": "Alfred",
        "Nom": "Durand",
        "Age": 25,
        "Loisirs": ["Machine learning", "Python", 
                    "Constructions en alumette"]}
eleve

{'Age': 25,
 'Loisirs': ['Machine learning', 'Python', 'Constructions en alumette'],
 'Nom': 'Durand',
 'Prénom': 'Alfred'}

In [18]:
eleve["Prénom"]

'Alfred'

In [19]:
eleve["Age"] += 1
eleve["Age"]

26

In [20]:
eleve.keys()

dict_keys(['Prénom', 'Nom', 'Age', 'Loisirs'])

In [21]:
eleve.values()

dict_values(['Alfred', 'Durand', 26, ['Machine learning', 'Python', 'Constructions en alumette']])

## Fonction

In [22]:
import random
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [23]:
def age_du_capitaine(taille_equipage: int, longueur_navire: int, port_depart: str):
    return random.randint(1, taille_equipage + longueur_navire + len(port_depart))

In [24]:
age_du_capitaine(taille_equipage=12, longueur_navire=50, 
                 port_depart="Marseille")

20

# Pandas

![title](pandas.jpg)

In [25]:
import pandas

In [26]:
df = pandas.DataFrame({"prenom": ["Alfred", "Yvette", "Georges"],
                      "age": [26, 22, 29],
                      "langage": ["python", "python", "java"]})
df

age langage   prenom
0   26  python   Alfred
1   22  python   Yvette
2   29    java  Georges

In [27]:
df.dtypes

age         int64
langage    object
prenom     object
dtype: object

In [28]:
df.loc[1, "age"]

22

In [29]:
df.loc[df.prenom == "Yvette", "age"]

1    22
Name: age, dtype: int64

In [30]:
df.langage.unique()

array(['python', 'java'], dtype=object)

In [31]:
df[df.langage == "python"]

age langage  prenom
0   26  python  Alfred
1   22  python  Yvette

In [32]:
df.groupby("langage").count()

age  prenom
langage             
java       1       1
python     2       2

In [33]:
def change_java_vers_scala(langage):
    if langage == "java":
        return "scala"
    return langage

df["langage"] = df.langage.apply(change_java_vers_scala)
df

age langage   prenom
0   26  python   Alfred
1   22  python   Yvette
2   29   scala  Georges

# Numpy

![title](numpy.png)

In [34]:
import numpy

## Tableau

In [35]:
t = numpy.array([[1, 2, 3], [4, 5, 6]])
t

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
t.shape

(2, 3)

## Opérations sur les tableaux

In [37]:
numpy.mean(t)

3.5

In [38]:
numpy.mean(t, axis=0)

array([2.5, 3.5, 4.5])

In [39]:
numpy.mean(t, axis=1)

array([2., 5.])

In [40]:
numpy.sum(t)

21

## Range nombres relatifs

In [41]:
numpy.linspace(-0.1, 0.2, 31)

array([-1.00000000e-01, -9.00000000e-02, -8.00000000e-02, -7.00000000e-02,
       -6.00000000e-02, -5.00000000e-02, -4.00000000e-02, -3.00000000e-02,
       -2.00000000e-02, -1.00000000e-02,  1.38777878e-17,  1.00000000e-02,
        2.00000000e-02,  3.00000000e-02,  4.00000000e-02,  5.00000000e-02,
        6.00000000e-02,  7.00000000e-02,  8.00000000e-02,  9.00000000e-02,
        1.00000000e-01,  1.10000000e-01,  1.20000000e-01,  1.30000000e-01,
        1.40000000e-01,  1.50000000e-01,  1.60000000e-01,  1.70000000e-01,
        1.80000000e-01,  1.90000000e-01,  2.00000000e-01])

## Échantillons aléatoires

In [42]:
numpy.random.choice(["chien", "chat"], size=10)

array(['chien', 'chat', 'chat', 'chat', 'chien', 'chien', 'chat', 'chat',
       'chat', 'chat'], dtype='<U5')

In [43]:
numpy.random.randint(0, 100, 5)

array([45, 98, 21, 37, 19])